(function(g){var window=this;var f6=function(a){var b={format:a.A,languageCode:a.o,languageName:a.D,displayName:g.AI(a),kind:a.B,name:a.C,id:a.Da,is_servable:a.N,is_translateable:a.G,vss_id:a.F};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},g6=function(a){return a.g?a.g.languageCode:a.o},ixa=function(a,b){var c=new g.zI;
c.o=a.o;c.D=a.D;c.C=a.C;c.B=a.B;c.G=a.G;c.F=a.F;c.I=a.I;c.g=b;return c},jxa=function(a){a=g.md(window.document,"track",void 0,a.g);
for(var b=0;b<a.length;b++)g.Hd(a[b])},kxa=function(a){for(var b in a)delete a[b]},lxa=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},h6=function(a){if(!mxa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(nxa,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},i6=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.CR.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.C=f;this.o=k},j6=function(a,b,c,d,e){g.CR.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},l6=function(a){a=void 0===a?{}:a;
var b="_"+k6++;return new j6(0,0x8000000000000,0,b,a)},m6=function(a,b,c,d,e,f){var k={};
g.Ga(k,b);g.Ga(k,a.params);g.Ga(k,c);var l={};g.Ga(l,b.qb);a.params.qb&&g.Ga(l,a.params.qb);g.Ga(l,c.qb);k.qb=l;g.Y.call(this,{H:"div",M:"caption-window",R:{id:"caption-window-"+a.id,dir:1==k.Uj?"rtl":"ltr",tabindex:0,"aria-live":"assertive",lang:k.lang},K:[{H:"span",M:"captions-text"}]});this.A=[];this.J=!1;this.F=a;this.D=[];this.G=[];this.ya=e;this.pa=f;this.C=null;this.U=.96*e;this.fa=.96*f;this.o=k;this.oa=c;this.B=this.sa["captions-text"];this.ia=null!=this.B.style["box-decoration-break"]||
null!=this.B.style["-webkit-box-decoration-break"];this.L=d/360*16;this.type=0;this.ba=this.L*oxa(l);a=new g.dG(this.element,!0);g.M(this,a);a.subscribe("dragstart",this.IK,this);a.subscribe("dragmove",this.HK,this);a.subscribe("dragend",this.GK,this);this.ea=this.da=0;a="";this.o.dk&&(a=h6(this.o.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.dk+")");b={"background-color":a,display:!1===this.o.isVisible?"none":"","text-align":pxa[this.o.textAlign]};this.ia&&(b["border-radius"]=a?this.ba/
8+"px":"");g.mh(this.element,b);switch(this.o.Og){case 0:case 1:case 2:g.R(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.R(this.element,"ytp-caption-window-bottom")}},oxa=function(a){var b=1+.25*(a.Wi||0);
if(0==a.offset||2==a.offset)b*=.8;return b},n6=function(a,b){var c={},d=b.background?b.background:a.o.qb.background;
if(null!=b.Pe||b.background){var e=null!=b.Pe?b.Pe:a.o.qb.Pe;d=h6(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.ia&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ba/8+"px")}if(null!=b.Wi||null!=b.offset)c["font-size"]=a.L*oxa(b)+"px";d=1;e=b.color||a.o.qb.color;if(b.color||null!=b.Bh)e=h6(e),d=null==b.Bh?a.o.qb.Bh:b.Bh,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Oh;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";
b.Kv&&(k=e=b.Kv);var l=a.L/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';
break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.ZE()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e=
'"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.o.qb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Dr&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");b.Tq&&(c.visibility="hidden");return c},qxa=function(a,b,c){a.J=a.J||!!c;
var d={};g.Ga(d,a.o.qb);g.Ga(d,c||b.o);g.Ga(d,a.oa.qb);c=a.D[0];if(c&&d.background==c.background&&d.Pe==c.Pe&&!!d.Tq==!!c.Tq&&d.Oh==c.Oh){var e;for(e=0;e<a.D.length;e++)if(lxa(d,a.D[e])){var f=a.G[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.Bd("SPAN");g.mh(f,n6(a,e));a.G[0].appendChild(f);e=1}a.G.length=e;a.D.length=e}else a.G.length=0,a.D.length=0,f=g.Bd("SPAN"),g.mh(f,n6(a,d)),a.B.appendChild(f);a.C&&a.C.parentNode!=f&&(g.Hd(a.C),f.appendChild(a.C));c=(k=g.u(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.A.length||!b.C){if(0<e||0!=a.A.length){var m=g.Bd("BR");f.appendChild(m)}f.appendChild(g.Cd("\u00a0"));a.C=g.Cd("\u00a0");f.appendChild(a.C)}l&&(m=a.C,m.parentNode&&m.parentNode.insertBefore(k?g.Cd(l):l,m))}a.D.push(d);a.G.push(f);a.A.push(b)},rxa=function(){},p6=function(a){this.F=a;
this.B=this.o=this.mode=this.A=0;this.C=new o6(this);this.D=new o6(this);this.g=[];this.clear()},txa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{tm:a,
wm:b,result:0};a=sxa[a];b=sxa[b];if(a&128){if(!(b&128)&&0!=c.g&&c.o==b)return{tm:a,wm:b,result:1}}else if(b&128&&1<=a&&31>=a)return{tm:a,wm:b,result:2};return{tm:a,wm:b,result:3}},vxa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.B&&a.reset(),a.C.g.clear(),a.D.g.clear()):(a.B=0,uxa(a.C,b,c,d))},wxa=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.o=d.time;0==d.type?vxa(a,d.Fv,d.Gv,b):1==d.type&&a.A&496&&uxa(a.D,d.Fv,d.Gv,b)}a.g.length=0},q6=function(){this.g=0},r6=function(){this.o=this.A=this.g=0},s6=function(){this.timestamp=this.pe=0;
this.g=!1},t6=function(a){this.A=[];
for(var b=0;15>=b;b++){this.A[b]=[];for(var c=0;32>=c;c++)this.A[b][c]=new s6}this.g=this.o=this.Dc=0;this.style=new q6;this.C=a;this.B=0},u6=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.C.o+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.A[m][q];
if(0!=r.pe){0==c&&(c=m,d=q);n=String.fromCharCode(r.pe);var w=r.timestamp;w<e&&(e=w);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.pe||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.o+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.A[k][m],r=q.pe,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),w=q.timestamp,w<=e&&(e=w),l+=n,q.reset()),32==m||0==r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},Bxa=function(a,b){switch(a){case 0:return xxa[(b&127)-32];
case 1:return yxa[b&15];case 2:return zxa[b&31];case 3:return Axa[b&31]}return 0},v6=function(a){return a.A[a.Dc][a.o]},w6=function(a,b,c){2<=b&&1<a.o&&(--a.o,v6(a).pe=0);
var d=v6(a);d.timestamp=a.C.o+0;d.pe=Bxa(b,c);32>a.o&&a.o++},Cxa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.A[b+e][f].Nm(a.A[c+e][f])},x6=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},y6=function(a){a.Dc=0<a.g?a.g:1;
a.o=1;x6(a,0,15)},z6=function(a){this.B=a;
this.C=0;this.style=new q6;this.D=new t6(a);this.F=new t6(a);this.G=new t6(a);this.o=this.D;this.A=this.F;this.g=this.o},A6=function(a,b,c){var d=a.o,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:u6(d,c),y6(a.o),y6(a.A),d.Dc=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.B.mode=1<<d.B;e?d.o=1:d.g!=b&&(d.g>b?(u6(d,c),x6(d,d.Dc-d.g,b)):d.Dc<b&&(b=d.g),d.g=b)},Dxa=function(a){a.style.set(1);
a.g=a.A;a.g.g=0;a.g.style=a.style;a.B.mode=1<<a.g.B},Exa=function(a){a.style.set(4);
a.g=a.G;a.g.style=a.style;a.B.mode=1<<a.g.B},o6=function(a){this.o=a;
this.g=new r6;this.C=0;this.A=new z6(a);this.D=new z6(a);this.B=this.A},uxa=function(a,b,c,d){a.g.update();
b=txa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.tm;c=b.wm;if(32<=e||!e)a.o.mode&a.o.A&&(b=e,b&128&&(b=127),c&128&&(c=127),e=a.B.g,b&96&&w6(e,0,b),c&96&&w6(e,0,c),!a.o.F&&0!=b&&0!=c&&3==e.style.g&&u6(e,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.A=e,b.o=c,b.g=2,b=e&8?a.D:a.A,a.B=b,a.o.mode=1<<(a.C<<2)+(b.C<<1)+(4==b.style.g?1:0),(a.o.mode|1<<(a.C<<2)+(b.C<<1)+(4!=b.style.g?1:0))&a.o.A))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&
14)>>1):0;c=b.g;switch(b.style.get()){case 4:d=c.Dc;break;case 3:if(d!=c.Dc){if(d<c.g&&(d=c.g,d==c.Dc))break;var f=1+c.Dc-c.g,k=1+d-c.g;Cxa(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));x6(c,b,e)}}c.Dc=d;c.o=a+1}else switch(e&7){case 1:switch(c&112){case 32:w6(b.g,0,32);break a;case 48:57==c?(b=b.g,v6(b).pe=0,32>b.o&&b.o++):w6(b.g,1,c&15)}break;case 2:c&32&&w6(b.g,2,c&31);break;case 3:c&32&&w6(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Dxa(b);break;
case 33:b=b.g;1<b.o&&(--b.o,v6(b).pe=0);break;case 36:b=b.g;d=v6(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.A[a][c]==d){for(;32>=c;c++)b.A[a][c].reset();break}break;case 37:A6(b,2,d);break;case 38:A6(b,3,d);break;case 39:A6(b,4,d);break;case 40:w6(b.g,0,32);break;case 41:b.style.set(2);b.g=b.o;b.g.g=0;b.g.style=b.style;b.B.mode=1<<b.g.B;break;case 42:d=b.G;d.g=15;d.style.set(4);y6(d);Exa(b);break;case 43:Exa(b);break;case 44:a=b.o;switch(b.style.get()){case 1:case 2:case 3:u6(a,d)}x6(a,0,15);break;
case 45:b:{a=b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Dc){++a.Dc;a.o=1;break b}case 3:}2>a.g&&(a.g=2,a.Dc<a.g&&(a.Dc=a.g));b=a.Dc-a.g+1;u6(a,d);Cxa(a,b,b+1,a.g-1);x6(a,a.Dc,1)}break;case 46:x6(b.A,0,15);break;case 47:u6(b.o,d);d=b.A;a=b.B.o+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.A[c][e].timestamp=a;d=b.A;b.A=b.o;b.o=d;Dxa(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.o+=c&3)&&(b.o=32)}}},B6=function(){},C6=function(a){this.A=a;
this.o=null},Gxa=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.lr("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");Fxa(d,e,k,b,f,a.firstChild,{},c)},Fxa=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.Dr=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");D6.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new i6(a,b,c,d,n.nodeValue,e||0<m,g.Xb(k)?void 0:k));else{var q={};g.Ga(q,k);Fxa(a,b,c,d,e||0<m,n,q,l)}}},E6=function(){this.A={};
this.o=null},F6=function(a){this.o={};
this.C={};this.D={};this.A="_"+k6++;this.B=a},G6=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},H6=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},I6=function(a,b){var c=G6(a,b);
if(void 0!=c)return c},J6=function(a,b){var c=a.getAttribute(b);
if(null!=c)return D6.test(c),c},Hxa=function(a,b){var c={},d=b.getAttribute("ws");
g.Ga(c,d?a.D[d]:a.B);d=I6(b,"mh");null!=d&&(c.Rr=d);d=I6(b,"ju");null!=d&&(c.textAlign=d);d=I6(b,"pd");null!=d&&(c.Uj=d);d=J6(b,"wfc");null!=d&&(c.windowColor=d);d=G6(b,"wfo");void 0!=d&&(c.dk=d/255);return c},Ixa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ga(c,a.C[d]);d=I6(b,"ap");null!=d&&(c.Og=d);d=G6(b,"cc");null!=d&&(c.EG=d);d=G6(b,"ah");null!=d&&(c.ii=d);d=G6(b,"rc");null!=d&&(c.Fo=d);d=G6(b,"av");null!=d&&(c.Fi=d);return c},Jxa=function(a,b,c){var d={};
g.Ga(d,Ixa(a,b));g.Ga(d,Hxa(a,b));c?lxa(d,a.B)?(c=a.A,d=a.B):c="_"+k6++:c=b.getAttribute("id")||"0";a=G6(b,"t");b=G6(b,"d")||0x8000000000000;return new j6(a,b,0,c,d)},K6=function(a,b,c){this.F=c;
this.version=this.C=this.D=this.g=0;this.o=new window.DataView(a);this.A=[]},L6=function(a){var b=a.g;
a.g+=1;return a.o.getUint8(b)},Kxa=function(a){var b=a.g;
a.g+=4;return a.o.getUint32(b)},M6=function(a,b){this.B=a;
this.o="CC3"==b.D?4:0;this.A=new p6(!1);this.A.A=1<<this.o},Lxa=function(a){if(!(a.g<a.o.byteLength))return!1;
var b=Kxa(a);b.toString(16);if(1380139777!=b)return!1;a.version=L6(a);if(1<a.version)return!1;L6(a);L6(a);L6(a);return!0},Mxa=function(){this.o=[];
this.g=[]},N6=function(a,b){return b?a.g.concat(a.o):a.g},O6=function(a,b){switch(b.B){case "asr":var c=a.o;
g.fb(c,(0,g.z)(b.J,b))||c.push(b);break;default:c=a.g,g.fb(c,(0,g.z)(b.J,b))||c.push(b)}},P6=function(){this.o=null},Nxa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Dr=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new i6(b,c,d,e.id,q.nodeValue,f||0<n,g.Xb(l)?void 0:l),m.push(q),e!=a.o&&e.o.push(q);else{var r={};g.Ga(r,l);Nxa(a,b,c,d,e,!0,q,r,m)}}},Q6=function(a){var b=0;
a=g.ma(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+c.value;return 1E3*b},R6=function(a){g.L.call(this);
this.Ux=!!a;this.o=new Mxa;this.C=[];this.g=null},Pxa=function(a){var b={};
if(a=g6(a))b.lang=a,Oxa.test(a)&&(b.Uj=1);return b},Qxa=function(a,b,c,d,e){d=d||0;
e=e||0;if(g.u(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new P6),a.g.g(b,d);b=g.lr(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new F6(Pxa(c)):a.g=new E6:a.g=new C6(Pxa(c)));return a.g.g(b,d)}try{if(g.u(b))var f=!1;else{var k=new K6(b,0,0);f=Lxa(k)}if(f)return a.g||(a.g=new M6(e,c)),a.g.g(b,d)}catch(l){g.yE(l)}return[]},S6=function(a){R6.call(this,a.Cm);
this.B=void 0;this.A=null;this.C=a.captionTranslationLanguages},T6=function(){this.ob=[]},U6=function(a,b,c,d,e,f){g.L.call(this);
this.J=b;this.B=new T6;this.g=null;this.D=d;this.I=f;this.o=this.A=null;this.L=c;this.C=e||!1;this.F=new g.ot(this.ly,1E3,this);g.M(this,this.F);this.G=new g.ZF(this);g.M(this,this.G);this.G.P(b,"seekto",this.Vy);this.Vy(b.getCurrentTime());this.ly()},V6=function(a,b){R6.call(this);
this.D=a;this.T=b;this.A=null;this.B=!1},W6=function(a,b,c,d,e,f){m6.call(this,a,b,c,d,e,f);
this.type=1},X6=function(a,b,c,d,e,f){m6.call(this,a,b,c,d,e,f);
g.R(this.element,"ytp-caption-window-rollup");this.type=2;this.I=this.N=0;this.O=window.NaN;this.ma=null;this.Y=new g.ot(this.zQ,433,this);g.M(this,this.Y)},Y6=function(a){if(!a.N){var b=g.Bd("SPAN");
g.mh(b,n6(a,a.o.qb));a.B.appendChild(b);b.appendChild(g.Cd("M"));var c=b.offsetHeight,d=g.Bd("BR");b.appendChild(d);b.appendChild(g.Cd("M"));a.N=b.offsetHeight-c;a.B.removeChild(b)}return a.N},Z6=function(a,b,c,d){R6.call(this,d);
c=c||g.JE(a).hl||"";c=c.split("_").join("-");this.D=g.LE(a,{hl:c});this.B=b;this.F={};this.A=null},b7=function(a){g.hX.call(this,a);
g.XD();this.B=g.X(a);this.A=a.ga();this.ia=g.nW(a);this.T=a;var b=null,c=g.sD("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.gD(c));this.ba=b;this.D={qb:{}};this.I={qb:{}};this.L=[];this.N={};this.aa={};this.Y=!1;this.ma="1"==this.A.Ub.cc_auto_caps||"1"==this.B.bb.cc_auto_caps;this.G="3"==this.B.B&&!!a.app.C&&!!a.app.C.g.textTracks;c=b=this.o=this.C=this.F=this.J=this.U=this.fa=null;this.G||(b=new g.lt(this.AC,void 0,this),g.M(this,b),c=new g.ot(this.iS,2E3,this),g.M(this,c));this.da=
b;this.ea=c;this.O=new g.ZF(this);g.M(this,this.O);this.G||this.O.P(a,"resize",this.Kt);this.O.P(a,"onPlaybackAudioChange",this.IN);this.O.P(a,"crn_captions",this.oK,this);this.O.P(a,"crx_captions",this.pK,this);$6(this,a7(this,"display-settings")||{})},Rxa=function(a){if(a.A.captionTracks.length)var b=a.g.th().Cv;
if("FORCED_ON"==b||1==a.B.Sg||1==a.A.Sg||"alwayson"==g.UP(a.A,"yt:cc"))return!0;if(2==a.B.Sg){var c=a7(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==g.UP(a.A,"yt:cc")},Sxa=function(a,b){if(a.C){var c=N6(a.C.o,b||a.ma);
if(a.F&&a.F.g)return a.F.g;for(var d=[a.A.Rg,a.B.Rg,g.UP(a.A,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(g6(c[f])==d[e])return c[f];return a.F&&a.F.jq?a.F.jq:c[0]||a.F&&a.F.yk}return null},Txa=function(a,b){for(var c=a.T.app.C.g.textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},c7=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.Y=c);a.o=b;a.load(d)},Uxa=function(a,b){var c=g.$Z(a.ia,!0).height;
if(!c)return null;var d=a.ia.Wa();switch(null!=b.params.Rr?b.params.Rr:b.params.PS?2:1<b.o.length?1:0){case 1:return new W6(b,a.D,a.I,c,d.width,d.height);case 2:return new X6(b,a.D,a.I,c,d.width,d.height);default:return new m6(b,a.D,a.I,c,d.width,d.height)}},$6=function(a,b,c){var d=d7.qb;
a.D={};g.Ga(a.D,d7);a.D.qb={};g.Ga(a.D.qb,d);a.I={qb:{}};var e=b.backgroundOverride?a.I:a.D,f=b.background||d.background;D6.test(f);e.qb.background=f;e=b.colorOverride?a.I:a.D;f=b.color||d.color;D6.test(f);e.qb.color=f;e=b.windowColorOverride?a.I:a.D;f=b.windowColor||d7.windowColor;D6.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.I:a.D;f=b.backgroundOpacity;null==f&&(f=d.Pe);e.qb.Pe=f;e=b.fontSizeIncrementOverride?a.I:a.D;f=b.fontSizeIncrement;null==f&&(f=d.Wi);e.qb.Wi=f;e=b.textOpacityOverride?
a.I:a.D;f=b.textOpacity;null==f&&(f=d.Bh);e.qb.Bh=f;e=b.windowOpacityOverride?a.I:a.D;f=b.windowOpacity;null==f&&(f=d7.dk);e.dk=f;e=b.charEdgeStyleOverride?a.I:a.D;f=b.charEdgeStyle;null==f&&(f=d.Oh);e.qb.Oh=f;e=b.fontFamilyOverride?a.I:a.D;f=b.fontFamily;null==f&&(f=d.fontFamily);e.qb.fontFamily=f;a.loaded&&a.Kt();c&&e7(a,"display-settings",b)},Wxa=function(a,b){if(b&&!a.J){var c=l6({Uj:0,
lang:"en"});a.J=[c,new i6(c.start,c.end-c.start,0,c.id,g.T("YTP_SAMPLE_SUBTITLES"))];g.zW(a.g,a.J)}else!b&&a.J&&(Vxa(a,a.J),a.J=null)},Vxa=function(a,b){g.BW(a.g,b);
(0,g.G)(b,function(a){g.rb(this.L,a)},a);
a.da.Hk()},Xxa=function(a,b){return a&&g.u(a)&&D6.test(a)?a:b},Yxa=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},$xa=function(a,b){if(a&&g.u(a)){var c=Zxa.indexOf(a);
return-1!=c?c:b}return b},bya=function(a,b){if(a&&g.u(a)){var c=aya.indexOf(a);
return-1!=c?c:b}return b},cya=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?g.Zc(a,-2,4):b},a7=function(a,b){if(!a.ba)return null;
try{var c=a.ba.get(b)}catch(d){a.ba.remove(b)}return c},e7=function(a,b,c){if(a.ba)try{a.ba.set(b,c)}catch(d){}};
g.AJ.prototype.pn=g.ca(4,function(a){return(a=this.Th(a))?a.o:0});
g.WL.prototype.pn=g.ca(3,function(){return 0});
g.zI.prototype.J=g.ca(2,function(a){return a?this.toString()==a.toString():!1});
var Oxa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,nxa=/#(.)(.)(.)/,mxa=/^#(?:[0-9a-f]{3}){1,2}$/i,D6=/^#(?:[0-9a-f]{3}){1,2}$/i,aya="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" "),Zxa=["none","raised","depressed","uniform","dropShadow"];var pxa=["left","right","center"];var d7={windowColor:"#080808",dk:0,textAlign:2,Og:7,ii:50,Fi:100,qb:{background:"#080808",Pe:.75,Oh:0,color:"#fff",fontFamily:4,Wi:0,Bh:1,offset:1}};g.p(i6,g.CR);g.p(j6,g.CR);var k6=0;g.p(m6,g.Y);g.h=m6.prototype;g.h.IK=function(a,b){var c=g.Ch(this.element,this.element.parentElement);this.da=a-c.x;this.ea=b-c.y;g.R(this.element,"ytp-dragging")};
g.h.HK=function(a,b){var c=g.Fh(this.element),d=a-this.da-.02*this.ya,e=b-this.ea-.02*this.pa,f=(d+c.width/2)/this.U*3;f=Math.floor(g.Zc(f,0,2));var k=(e+c.height/2)/this.fa*3;k=Math.floor(g.Zc(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.U;d=100*g.Zc(d,0,1);c=(e+k/2*c.height)/this.fa;c=100*g.Zc(c,0,1);this.F.params.Og=l;this.F.params.Fi=c;this.F.params.ii=d;this.o.Og=l;this.o.Fi=c;this.o.ii=d;this.zB()};
g.h.GK=function(){g.Gp(this.element,"ytp-dragging")};
g.h.zB=function(){this.Ci(this.A)};
g.h.Vb=function(){return this.type};
g.h.Ci=function(a){var b=Math.min(this.Nw(),this.U),c=this.Mw();g.mh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Mp(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.o.ii+2,e=this.o.Og;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.B.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.o.Fi+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.mh(this.element,a)};
g.h.Mp=function(a){var b;for(b=0;b<a.length&&a[b]==this.A[b];b++);if(this.J||this.A.length>b)b=0,this.J=!1,this.A=[],this.D=[],this.G=[],this.C=null,g.Fd(this.B);for(;b<a.length;b++)qxa(this,a[b])};
g.h.Nw=function(){return 0};
g.h.Mw=function(){return 0};
g.h.toString=function(){return g.Y.prototype.toString.call(this)};rxa.prototype.B=function(){};p6.prototype.clear=function(){this.B=this.o=this.mode=0;this.g=[];this.reset()};
p6.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var sxa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];q6.prototype.set=function(a){this.g=a};
q6.prototype.get=function(){return this.g};
r6.prototype.clear=function(){this.g=0};
r6.prototype.update=function(){this.g=2==this.g?1:0};
r6.prototype.matches=function(a,b){return 0!=this.g&&a==this.A&&b==this.o};
s6.prototype.Nm=function(a){this.pe=a.pe;this.timestamp=a.timestamp;this.g=a.g};
s6.prototype.reset=function(){this.timestamp=this.pe=0;this.g=!1};
t6.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.A[b][c];a=0==d.pe?a+"_":a+String.fromCharCode(d.pe)}a+="\n"}return a};
t6.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.g=0;this.o=this.Dc=1};
var xxa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],yxa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],zxa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Axa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];z6.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.o=this.D;this.A=this.F;this.g=this.o;var c=(a<<2)+(b<<1)+0;this.D.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
o6.prototype.reset=function(a){this.C=a;this.g.clear();this.B=this.A;this.A.reset(a,0);this.D.reset(a,1)};B6.prototype.reset=function(){};g.p(C6,B6);C6.prototype.g=function(a){var b=[];this.o||(this.o=l6(this.A),b.push(this.o));a=g.ma(a.firstChild.childNodes);for(var c=a.next();!c.done;c=a.next())Gxa(c.value,this.o.id,b);return b};g.p(E6,B6);
E6.prototype.g=function(a){var b=[];this.o||(this.o=l6(),this.A[this.o.id]=this.o,b.push(this.o));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.A[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=l6());
var k={};f&&(g.Ga(k,f.params),f=f.params.qb)&&(k.qb={},g.Ga(k.qb,f));e.getAttribute("rc")&&(k.Fo=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.EG=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Og=0>f||8<f?7:f);e.getAttribute("ah")&&(k.ii=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.Fi=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.Uj=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.Uj=0));e.getAttribute("bc")&&(k.qb||(k.qb={}),k.qb.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.qb||(k.qb={}),k.qb.Pe=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.qb||(k.qb={}),k.qb.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.PS=(0,window.parseInt)(e.getAttribute("sd"),10));f=(0,window.parseInt)(e.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new j6(c,f,0,e,k)}else c=null}this.A[d]=c;b.push(c);break;case "text":for(d=[],Gxa(a,this.o.id,d),d=g.ma(d),c=d.next();!c.done;c=d.next())c=c.value,this.A[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(F6,B6);
F6.prototype.g=function(a){a.firstChild.getAttribute("format");a=g.ma(a.firstChild.childNodes);for(var b=a.next();!b.done;b=a.next())switch(b=b.value,b.tagName){case "head":var c=b;break;case "body":var d=b}if(c)for(c=g.ma(c.childNodes),a=c.next();!a.done;a=c.next())switch(a=a.value,a.tagName){case "pen":b=a.getAttribute("id");var e=this.o,f={},k=a.getAttribute("p");k&&g.Ga(f,this.o[k]);k=H6(a,"b");null!=k&&(f.bold=k);k=H6(a,"i");null!=k&&(f.Dr=k);k=H6(a,"u");null!=k&&(f.underline=k);k=I6(a,"et");
null!=k&&(f.Oh=k);k=I6(a,"of");null!=k&&(f.offset=k);k=J6(a,"bc");null!=k&&(f.background=k);k=J6(a,"ec");null!=k&&(f.Kv=k);k=J6(a,"fc");null!=k&&(f.color=k);k=I6(a,"fs");void 0!=k&&0!=k&&(f.fontFamily=k);k=G6(a,"sz");void 0!=k&&(f.Wi=k/100-1);k=G6(a,"bo");void 0!=k&&(f.Pe=k/255);a=G6(a,"fo");void 0!=a&&(f.Bh=a/255);e[b]=f;break;case "ws":b=a.getAttribute("id");this.D[b]=Hxa(this,a);break;case "wp":b=a.getAttribute("id"),this.C[b]=Ixa(this,a)}c=[];if(d)for(a={},b=void 0,d=g.ma(d.childNodes),e=d.next();!e.done;e=
d.next())switch(e=e.value,e.tagName){case "w":var l=Jxa(this,e,!1);(e=a[l.id])&&e.end>l.start&&(e.end=l.start);a[l.id]=l;c.push(l);break;case "p":var m=b,n=Rc;f=[];k=e.getAttribute("w")||this.A;var q=!!H6(e,"a"),r=G6(e,"t")||0,w=G6(e,"d")||5E3;!n&&!q&&m&&m.windowId==k&&m.end>r&&(m.end=r);m=q?6:5;n=this.o[e.getAttribute("p")];for(var B=e.childNodes,D=0;D<B.length;D++){var I=B[D];0<D&&(q=!0);if("s"==I.tagName){var U=I;I=r;var ka=w,Ma=k,Da=q,Fa=m,Ff=U.textContent?U.textContent:"",kb=this.o[U.getAttribute("p")];
U=G6(U,"t")||0;I=new i6(I+U,ka-U,Fa,Ma,Ff,Da,kb)}else I=new i6(r,w,m,k,I.textContent||"",q,n);f.push(I)}b&&"\n"==b.text&&(b.text="");if(0<f.length){b=f[f.length-1];var Rc=null!=e.getAttribute("d");f[0].windowId==this.A&&(l=Jxa(this,e,!0),c.push(l));e=g.ma(f);for(f=e.next();!f.done;f=e.next())f=f.value,f.windowId=l.id,l.o.push(f),c.push(f)}}return c};g.p(K6,rxa);K6.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+k6++;c=c/1E3-this.F;d=d/1E3-this.F;a=new j6(c,d-c,5,f,{textAlign:0,Og:0,ii:2.5*b,Fi:5.33*a});e=new i6(c,d-c,5,f,e);this.A.push(a);this.A.push(e)}};
g.p(M6,B6);M6.prototype.g=function(a){a=new K6(a,0,this.B);if(Lxa(a)){for(;a.g<a.o.byteLength;)for(0==a.version&&(a.D=Kxa(a)*(1E3/45)),a.C=L6(a);0<a.C;a.C--){var b=L6(a),c=L6(a),d=L6(a);b&4&&(b&3)==this.o&&(0==this.o||1==this.o)&&(b=this.A,b.g.push({time:a.D,type:this.o,Fv:c,Gv:d,order:b.g.length}))}wxa(this.A,a);return a.A}return[]};
M6.prototype.reset=function(){this.A.clear()};g.p(P6,B6);
P6.prototype.g=function(a,b){for(var c=[],d=a.split(dya),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!eya.test(f)){var l=f7.exec(f);if(l&&3<=l.length){var m=Q6(l[1]);l=Q6(l[2])-m;m+=k;f=f.substring(f7.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");f7.lastIndex=0;var n=f;f={};this.o||(this.o=l6({Rr:0}),c.push(this.o));var q=this.o;k=5;if(0>n.indexOf("<")&&0>n.indexOf("&"))c.push(new i6(m,l,k,q.id,n,!1,g.Xb(f)?void 0:f));else{n=n.split(fya);1!=n.length&&(k=6,q="_"+gya++,q=new j6(m,l,k,q,{}),c.push(q));
for(var r=m,w=0;w<n.length;w++){var B=n[w];if(0==w%2){var D=g.lr("<html>"+B+"</html>");if(D.getElementsByTagName("parsererror").length){var I=D.createElement("span");I.appendChild(D.createTextNode(B))}else I=D.firstChild;Nxa(this,r,l-(r-m),k,q,0<w,I,f,c)}else r=Q6(B)}}}f7.lastIndex=0}}return c};
var gya=0,eya=/^NOTE/,dya=/(?:\r\n|\r|\n){2,}/,f7=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3}).*(?:\r\n|\r|\n)","gm"),fya=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.p(R6,g.L);R6.prototype.Gd=function(){this.g=null};
R6.prototype.X=function(){g.L.prototype.X.call(this);this.Gd()};
R6.prototype.kB=function(){return!1};g.p(S6,R6);g.h=S6.prototype;g.h.Lr=function(a,b){var c=this.Fk(a),d=(0,g.z)(function(c){this.A=null;b(c.responseText,a)},this);
this.Gd();this.A=g.SE(c,{format:"RAW",Tb:d,withCredentials:!0})};
g.h.Mr=function(a,b,c,d){this.B=c;if(d)for(b=g.ma(d.captionTracks),c=b.next();!c.done;c=b.next())O6(this.o,c.value);a()};
g.h.Fk=function(a){var b=a.I,c={};if(this.B||a.A)c.fmt=this.B||"srv"+a.A;a.g&&(c.tlang=a.g.languageCode);return g.LE(b,c)};
g.h.Gd=function(){R6.prototype.Gd.call(this);this.A&&this.A.abort()};
g.h.X=function(){this.Gd();R6.prototype.X.call(this)};T6.prototype.contains=function(a){a=g.Bb(this.ob,a);return 0<=a||0>a&&1==(-a-1)%2};
T6.prototype.length=function(){return this.ob.length/2};g.p(U6,g.L);g.h=U6.prototype;g.h.X=function(){g.L.prototype.X.call(this);this.o&&this.o.abort()};
g.h.Vy=function(a){var b=this.g;this.g=g.db(this.L.dh(a).g);b!=this.g&&this.I&&this.I()};
g.h.reset=function(){this.B=new T6;this.o&&(this.o.abort(),this.o=null)};
g.h.ly=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.li(a);if(a&&!this.o&&!(this.g&&30<this.g.startTime-this.J.getCurrentTime())){a=this.g;a=a.g.Wk(a);if(!this.B.contains(a.g[0].ua)){var b=g.AL(g.HL(a,{})),c={format:"RAW",Ed:(0,g.z)(this.vQ,this),withCredentials:!0};this.C&&(c.responseType="arraybuffer");this.o=g.SE(b,c);this.A=a;b=this.B;c=this.A.g[0].ua;var d=g.Bb(b.ob,c);0<=d||0>d&&1==(-d-1)%2||(d=-d-1,0<d&&1==c-b.ob[d-1]&&d<b.ob.length&&1==b.ob[d]-c?(g.qb(b.ob,d),g.qb(b.ob,d-1)):0<d&&1==
c-b.ob[d-1]?b.ob[d-1]=c:d<b.ob.length&&1==b.ob[d]-c?b.ob[d]=c:(g.xb(b.ob,d,0,c),g.xb(b.ob,d+1,0,c)))}this.g=g.db(a.g)}this.F.start()};
g.h.vQ=function(a){(this.C?!a.response:!a.responseText)||400<=a.status||null===this.D||(this.C?this.D(a.response,1E3*this.A.g[0].startTime):this.D(a.responseText,1E3*this.A.g[0].startTime));this.o=this.A=null};g.p(V6,R6);g.h=V6.prototype;g.h.Lr=function(a,b){this.Gd();var c=this.D.g[a.o];if(c){var d=1E3*c.index.pn(c.index.ng()),e=g.X(this.T).qe;this.A=new U6(new g.bL,this.T,c,function(c,e){b(c,a,e,d)},e,(0,g.z)(function(){e&&(this.A&&this.A.reset(),this.g&&this.g.reset(),this.B=!0)},this))}};
g.h.kB=function(){var a=this.B;this.B=!1;return a};
g.h.Mr=function(a){g.X(this.T).qe?(O6(this.o,new g.zI({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),O6(this.o,new g.zI({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}))):O6(this.o,new g.zI({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.Gd=function(){R6.prototype.Gd.call(this);this.A&&(this.A.dispose(),this.A=null)};
g.h.Fk=function(){return""};
g.h.X=function(){this.Gd();R6.prototype.X.call(this)};g.p(W6,m6);W6.prototype.Mp=function(a){var b=this.F.o;m6.prototype.Mp.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Ga(d,c.o);g.Ga(d,hya);var e=c.o;var f=d}qxa(this,c,d)}};
var hya={Tq:!0};g.p(X6,m6);g.h=X6.prototype;g.h.zB=function(){g.qt(this.Y)};
g.h.zQ=function(){g.Gp(this.element,"ytp-rollup-mode");this.Ci(this.ma,!0)};
g.h.Nw=function(){return this.I};
g.h.Mw=function(){return this.F.params.Fo*Y6(this)};
g.h.Ci=function(a,b){this.ma=a;if(Y6(this)){for(var c=0,d=0;d<this.A.length&&c<a.length;d++)this.A[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.A.concat(a.slice(c)));c=this.I;this.I=0;m6.prototype.Ci.call(this,a);this.I=Math.max(c,this.B.offsetWidth+1);c=this.F.params.Fo*Y6(this)-this.B.offsetHeight;c!=this.O&&(b||(0,window.isNaN)(this.O)||(g.R(this.element,"ytp-rollup-mode"),g.pt(this.Y)),g.mh(this.B,"transform",c?"translateY("+c+"px)":""),this.O=c);m6.prototype.Ci.call(this,a)}else m6.prototype.Ci.call(this,
a)};g.p(Z6,R6);g.h=Z6.prototype;g.h.Lr=function(a,b){var c=this.Fk(a),d=(0,g.z)(function(c){this.A=null;b(c.responseText,a)},this);
this.Gd();this.A=g.SE(c,{format:"RAW",Tb:d,withCredentials:!0})};
g.h.Mr=function(a,b,c){var d=this.D;b={type:"list",tlangs:1,v:this.B,fmts:Number(b||!1),vssids:1};this.Ux&&(b.asrs=1);d=g.LE(d,b);b=(0,g.z)(function(b){this.A=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.o,e=g.ma(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),w=m.getAttribute("kind"),B=m.getAttribute("id"),D="true"==m.getAttribute("cantran");
m=m.getAttribute("vss_id");O6(d,new g.zI({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:w,id:B,is_servable:!0,is_translateable:D,vss_id:m}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),l={languageCode:l,languageName:n,languageOriginal:q,id:r},this.F[l.languageCode]=l.languageName,this.C.push(new g.yI(l))}a()},this);
this.Gd();this.A=g.SE(d,{format:"RAW",Tb:b,withCredentials:!0})};
g.h.Fk=function(a){var b=this.D,c={v:this.B,type:"track",lang:a.o,name:a.C,kind:a.B,fmt:a.A};a.g&&(c.tlang=g6(a));return b=g.LE(b,c)};
g.h.Gd=function(){R6.prototype.Gd.call(this);this.A&&this.A.abort()};
g.h.X=function(){this.Gd();R6.prototype.X.call(this)};g.p(b7,g.hX);g.h=b7.prototype;g.h.X=function(){if(this.G){var a=this.T.app.C;a&&jxa(a)}else Wxa(this,!1);g.hX.prototype.X.call(this)};
g.h.Ny=function(){return this.G?!this.A.xa:this.A.captionTracks.length&&this.g.th().yk?!0:Rxa(this)};
g.h.load=function(a){g.hX.prototype.load.call(this);this.F=this.g.th();if(this.C||a)this.o?(this.G&&!this.B.experiments.g("disable_native_caption_api")?Txa(this,!0):a?this.UA(a,this.o):3!=this.g.Va()&&this.C.Lr(this.o,(0,g.z)(this.UA,this)),this.g.va("captionschanged",f6(this.o))):this.g.va("onCaptionsTrackListChanged");else{var b;a=this.A;a.xa||g.X(this.T).qe&&null!=a.ra&&null!=a.ra.g.rawcc?b=new V6(this.A.ra,this.g):this.A.captionTracks.length?b=new S6(this.A):b=new Z6(this.A.Dm,this.A.videoId,
this.A.Rg||this.B.Rg||g.UP(this.A,"yt:cc_default_lang")||this.B.Qa,this.A.Cm);this.C=b;b.Mr((0,g.z)(this.bR,this),!0,this.G?"vtt":void 0,this.g.th())}};
g.h.unload=function(){this.G?this.B.experiments.g("disable_native_caption_api")?jxa(this.T.app.C):this.o&&Txa(this,!1):(this.ea&&g.rt(this.ea),g.CW(this.g,"captions"),this.L=[],this.C&&this.C.Gd(),this.J&&g.zW(this.g,this.J),this.Kt());g.hX.prototype.unload.call(this);var a=g.lW(this.g.app);a&&a.D&&g.lQ(a.D.A);this.g.va("captionschanged",{})};
g.h.bR=function(){if(this.Y||Rxa(this))var a=Sxa(this,this.Y);if(this.G){for(var b=N6(this.C.o,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.AI(e),srclang:g6(e),src:this.C.Fk(e),id:e.toString()};e==a&&(f["default"]=1);c.push(g.zd("TRACK",f))}a=this.T.app.C;for(b=0;b<c.length;b++)a.g.appendChild(c[b]);(c=this.T.app.C.g)&&c.textTracks&&c.textTracks.addEventListener&&!this.B.experiments.g("disable_native_caption_api")&&this.O.P(c.textTracks,"change",this.cR)}else!this.o&&a&&c7(this,
a),this.g.va("onCaptionsTrackListChanged"),this.g.va("onApiChange")};
g.h.cR=function(){for(var a=this.T.app.C.g.textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=N6(this.C.o,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.o:null)!=b&&c7(this,b,!0)};
g.h.XS=function(){this.B.experiments.g("disable_native_caption_api")?this.loaded&&!this.G&&this.unload():!this.o&&this.G||this.unload()};
g.h.UA=function(a,b,c,d){if(a){this.C.kB()&&(this.L=[],g.CW(this.T,"captions"),this.da.Hk());a=Qxa(this.C,a,b,c,d);c={trackName:b.C,trackKind:b.B,trackLangCode:g6(b)};b.g&&(c.fromLangCode=b.o);g.tW(this.g,"cc",c);if(this.o!=(this.F&&this.F.yk)){if(this.Y&&!g.CN(this.B)&&!g.TN(this.B)){g.rt(this.ea);b=l6({Og:0,ii:5,Fi:5,Fo:2,textAlign:0,Uj:0,lang:"en"});this.U=[b];c=g.T("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON");this.fa||(d=new g.OW(g.qE()),g.M(this,d),this.fa=d.element);d=b.end-b.start;var e=g.AI(this.o);
e&&this.U.push(new i6(b.start,d,0,b.id,e));this.U.push(new i6(b.start,d,0,b.id,c[0]),new i6(b.start,d,0,b.id,this.fa,!0),new i6(b.start,d,0,b.id,c[1],!0));g.zW(this.g,this.U);g.pt(this.ea)}if(this.Y||g.CN(this.B))e7(this,"module-enabled",!0),this.F&&(this.F.g=this.o);(b=g.lW(this.g.app))&&b.D&&g.lQ(b.D.A)}g.zW(this.g,a);this.Y=!1}};
g.h.oK=function(a){this.L.push(a);this.da.Hk()};
g.h.pK=function(a){g.rb(this.L,a);this.da.Hk()};
g.h.VR=function(a){if(a instanceof j6){var b=this.N[a.id];b&&b.F!=a&&(b.dispose(),delete this.N[a.id],b=null);b||(b=Uxa(this,a))&&(this.N[a.id]=b)}else b=a.windowId,this.aa[b]||(this.aa[b]=[]),this.aa[b].push(a)};
g.h.iS=function(){Vxa(this,this.U);this.U=null};
g.h.AC=function(){this.da.stop();kxa(this.aa);this.L.sort(g.ER);var a=this.L;if(this.J){var b=(0,g.Jd)(a,function(a){return-1==this.J.indexOf(a)},this);
b.length&&(a=b)}(0,g.G)(a,this.VR,this);g.Jb(this.N,function(a,b){this.aa[b]?(a.element.parentNode||g.GW(this.g,a.element,4),a.Ci(this.aa[b])):(a.dispose(),delete this.N[b])},this)};
g.h.yB=function(){$6(this,{},!0)};
g.h.Cq=function(){var a=d7.qb;a={background:a.background,backgroundOpacity:a.Pe,charEdgeStyle:a.Oh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.Wi,textOpacity:a.Bh,windowColor:d7.windowColor,windowOpacity:d7.dk};var b=a7(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Nt=function(a,b){var c={};g.Ga(c,a7(this,"display-settings"));g.Ga(c,a);$6(this,c,b);this.g.V("captionssettingschanged")};
g.h.Kt=function(){!this.G&&this.loaded&&(g.Jb(this.N,function(a,b){a.dispose();delete this.N[b]},this),this.AC())};
g.h.Xr=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.Zc(b,-2,4);this.Nt({fontSizeIncrement:c});return c;case "reload":b&&!this.G&&c7(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.B.Fb&&e7(this,"module-enabled",!!b);break;case "track":if(!this.C)return{};if(b){if(this.G)break;if(!g.Aa(b))break;if(g.Xb(b)){c7(this,null,!0);break}for(var d=N6(this.C.o,!0),e=0;e<d.length;e++){var f=d[e];f.o!=b.languageCode||c&&f.D!=b.languageName||(c=b.translationLanguage?ixa(f,
b.translationLanguage):f)}!c||c==this.o&&this.loaded||c7(this,c,!0)}else return this.loaded&&this.o&&this.o!=(this.F&&this.F.yk)?f6(this.o):{};return"";case "tracklist":return this.C?(0,g.J)(N6(this.C.o,b&&b.includeAsr),function(a){return f6(a)}):[];
case "translationLanguages":return this.C?this.C.C:[];case "displaySettings":c=this.Cq();if(g.CN(this.B)&&b&&g.Aa(b))if(b.reset)this.yB();else{f={};for(d in b)switch(d){case "color":case "background":case "windowColor":f[d]=Xxa(b[d],c[d]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[d]=Yxa(b[d],c[d]);break;case "charEdgeStyle":f[d]=$xa(b[d],c[d]);break;case "fontSizeIncrement":f[d]=cya(b[d],c[d]);break;case "fontFamilyOption":f.fontFamily=bya(b[d],c[d])}for(e in f)f[e+
"Override"]=!0;this.Nt(f,!0);c=this.Cq()}c.fontFamilyOption=aya[c.fontFamily];c.charEdgeStyle=Zxa[c.charEdgeStyle];return c;case "sampleSubtitles":this.G||void 0==b||Wxa(this,!!b);break;case "xmlTrack":b&&this.B.Fb&&(this.G||c7(this,new g.zI({languageName:b.name}),!1,b.xml))}};
g.h.mK=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.B.Fb&&a.push("stickyLoading","xmlTrack");return a};
g.h.nK=function(){var a=this.o;return a?{cc:a.F}:{}};
g.h.nC=function(){this.loaded&&this.o?(e7(this,"module-enabled",!1),this.unload()):c7(this,this.o||Sxa(this,!0),!0)};
g.h.IN=function(){this.A.captionTracks.length&&(this.loaded&&this.unload(),this.Ny()&&this.load())};g.UZ.captions=b7;})(_yt_player);
